In [1]:
import pandas as pd

df=pd.read_csv('D:\Dizertatie\Money_Laundering_project\media\inference\graph_preprocessor.csv')

<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Superuser\AppData\Local\Temp\ipykernel_3152\55829926.py:3: SyntaxWarning: invalid escape sequence '\D'
  df=pd.read_csv('D:\Dizertatie\Money_Laundering_project\media\inference\graph_preprocessor.csv')

In [3]:
df.tail()

,EdgeID,from_id,to_id,Timestamp,feature_0,feature_1,feature_2,feature_3,time_window,vertex_stats_time_window,...,dest_skew_col3_out,dest_kurtosis_col3_out,dest_fan_in,dest_deg_in,dest_ratio_in,dest_avg_col3_in,dest_sum_col3_in,dest_var_col3_in,dest_skew_col3_in,dest_kurtosis_col3_in
5078340,5078340,65000,75723,1515730.0,3749.14,0.0,3749.14,0.0,4.0,1.0,...,-0.253774,1.605485,4.0,43.0,10.750000,4.660133e+05,20038570.0,1.112303e+11,1.123895,5.130661
5078341,5078341,65000,65000,1520290.0,2091.95,0.0,1785.27,1.0,4.0,0.0,...,-0.159942,1.395996,12.0,41.0,3.416667,6.559607e+05,26894390.0,2.054725e+11,0.294277,1.997142
5078342,5078342,65000,201521,1520290.0,1785.27,1.0,1785.27,1.0,4.0,1.0,...,0.000000,0.000000,2.0,3.0,1.500000,1.017530e+06,3052590.0,5.055352e+11,-0.707107,1.500000
5078343,5078343,65000,275383,1526290.0,2154.54,0.0,2154.54,0.0,4.0,1.0,...,-0.572660,1.819303,4.0,7.0,1.750000,7.165300e+05,5015710.0,3.275977e+11,0.387986,1.564307
5078344,5078344,65000,206627,1538290.0,5448.55,0.0,5448.55,0.0,4.0,1.0,...,-0.510968,1.723432,6.0,48.0,8.000000,4.748425e+05,22792440.0,1.200340e+11,0.923388,4.337610

In [1]:
import pandas as pd
df2=pd.read_csv('D:\Dizertatie\Money_Laundering_project\media\inference\\GFP_transactions.csv')
df2.head()

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Superuser\AppData\Local\Temp\ipykernel_1264\326572054.py:2: SyntaxWarning: invalid escape sequence '\D'
  df2=pd.read_csv('D:\Dizertatie\Money_Laundering_project\media\inference\\GFP_transactions.csv')

,EdgeID,from_id,to_id,Timestamp,Amount Sent,Sent Currency,Amount Received,Received Currency,Payment Format,Is Laundering,...,dest_skew_col3_out,dest_kurtosis_col3_out,dest_fan_in,dest_deg_in,dest_ratio_in,dest_avg_col3_in,dest_sum_col3_in,dest_var_col3_in,dest_skew_col3_in,dest_kurtosis_col3_in
0,23,26,26,10810.0,21163.90,0.0,21163.90,0.0,0.0,0.0,...,-0.260635,1.513414,2.0,5.0,2.500000,119422.000000,597110.0,3.697402e+09,-0.914873,2.219437
1,22,25,25,10810.0,560045.98,0.0,560045.98,0.0,0.0,0.0,...,-0.146029,1.706108,3.0,43.0,14.333333,428881.627907,18441910.0,5.984993e+10,-0.374870,1.763814
2,21,23,24,10810.0,65669.07,0.0,65669.07,0.0,1.0,0.0,...,-0.124785,1.803126,4.0,36.0,9.000000,375051.666667,13501860.0,6.501160e+10,0.243423,1.760148
3,20,22,22,10810.0,145397.31,0.0,145397.31,0.0,0.0,0.0,...,-0.068259,1.622121,3.0,46.0,15.333333,417536.956522,19206700.0,7.178245e+10,0.060290,1.635848
4,19,21,21,10810.0,21.53,0.0,21.53,0.0,0.0,0.0,...,0.679051,1.501283,2.0,3.0,1.500000,159310.000000,477930.0,4.381999e+10,0.707096,1.500000

In [3]:
df2['dest_fan_in']

0           2.0
1           3.0
2           4.0
3           3.0
4           2.0
           ...
5078340     4.0
5078341    12.0
5078342     2.0
5078343     4.0
5078344     6.0
Name: dest_fan_in, Length: 5078345, dtype: float64

In [7]:
renamed_df = df.rename(columns={
    'feature_0': 'Amount Sent',
    'feature_1': 'Sent Currency',
    'feature_2': 'Amount Received',
    'feature_3': 'Received Currency',
    'time_window': 'Payment Format',
    'vertex_stats_time_window': 'Is Laundering',
})

renamed_df.to_csv('renamed_dataframe.csv', index=False)

In [8]:
renamed_df.head()

,EdgeID,from_id,to_id,Timestamp,Amount Sent,Sent Currency,Amount Received,Received Currency,Payment Format,Is Laundering,...,dest_skew_col3_out,dest_kurtosis_col3_out,dest_fan_in,dest_deg_in,dest_ratio_in,dest_avg_col3_in,dest_sum_col3_in,dest_var_col3_in,dest_skew_col3_in,dest_kurtosis_col3_in
0,23,26,26,10810.0,21163.90,0.0,21163.90,0.0,0.0,0.0,...,-0.260635,1.513414,2.0,5.0,2.500000,119422.000000,597110.0,3.697402e+09,-0.914873,2.219437
1,22,25,25,10810.0,560045.98,0.0,560045.98,0.0,0.0,0.0,...,-0.146029,1.706108,3.0,43.0,14.333333,428881.627907,18441910.0,5.984993e+10,-0.374870,1.763814
2,21,23,24,10810.0,65669.07,0.0,65669.07,0.0,1.0,0.0,...,-0.124785,1.803126,4.0,36.0,9.000000,375051.666667,13501860.0,6.501160e+10,0.243423,1.760148
3,20,22,22,10810.0,145397.31,0.0,145397.31,0.0,0.0,0.0,...,-0.068259,1.622121,3.0,46.0,15.333333,417536.956522,19206700.0,7.178245e+10,0.060290,1.635848
4,19,21,21,10810.0,21.53,0.0,21.53,0.0,0.0,0.0,...,0.679051,1.501283,2.0,3.0,1.500000,159310.000000,477930.0,4.381999e+10,0.707096,1.500000